# Site settings
title: Mohamed's Blog
description: "A minimal blog is all what I need."
url: "https://wakematta.github.io"
author:
  name: "Mohamed Ziata"
  email: "wakematta@gmail.com.com"
  url: "https://wakematta.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
